<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>cbbab478-ee03-4df7-8587-26fa0c637e84</testSuiteGuid>
   <testCaseLink>
      <guid>6eab36b2-d945-4796-8976-efe31fc1049e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/LoginAdmin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d84ff3e2-1cc6-45a2-9b5d-82871f2c18bd</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/Servers</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d84ff3e2-1cc6-45a2-9b5d-82871f2c18bd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Links</value>
         <variableId>bcde9f71-3495-49f6-a85c-d105464074e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3a1d02b-4320-448e-8e38-ed91be63f952</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c9e890d-c538-4b36-9e57-7c11f7376e5f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bdde2724-746f-47c2-8ed4-09a0b5bc32fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DailyRates</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
