<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>POR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>04cbd3f5-de9a-4de3-a43b-4ed12a2ee544</testSuiteGuid>
   <testCaseLink>
      <guid>90f8d510-b058-47cb-8c96-e13eb2ff8aba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/LoginAdmin</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcde9f71-3495-49f6-a85c-d105464074e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9690517-104d-42e0-a1ac-3feb1f58f388</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/POR/POR</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4e98195c-6262-4dfa-b703-52ee4a1da229</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Materials/Materials IDless</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>908a2910-e004-481b-91be-6260816a5f2d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Warehouses</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>3d38c7f5-9175-4b85-a76c-b5d8558a754c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Materials/Materials Service</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e10772fe-4fc0-4680-bfc4-062c30d43a96</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Materials/Materials SN_FN</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>3d38c7f5-9175-4b85-a76c-b5d8558a754c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>material_name</value>
         <variableId>f80176e9-3dca-42fd-b293-83a2fcb6acf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0adfccc1-58be-4845-9580-3cbe98cdebf2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
