<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SD-PO from LOGIN</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>10</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>1d5bb4a3-1fa5-4951-aad4-5ff7a18aa10e</testSuiteGuid>
   <testCaseLink>
      <guid>1c0a4311-b794-4b97-b0b9-421d33181826</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/LoginAdmin</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e2ac997-6282-4657-8a79-3f25764949ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9a23b9a-cbc9-4eae-ae7b-bda72dfbdda0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ad813a2-c2ad-43f6-b6f2-2a87a6710071</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c9c7623-1cd3-4eca-92ce-3211cce9e5a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c3a78bd-e34e-4525-abe0-f9b2414271b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cc5dc4b-4a32-4903-9113-88419a11c838</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9548b45-20ab-46ae-ae9e-a62e56c5d506</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>522e4770-5c3c-40c4-8d1f-d8cce2480eaa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>023e79f1-2ff9-41e5-aeb1-e72a16800e2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>453d3178-0763-4b1f-a66a-9f4f9a0cc856</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be44f115-6c6b-4f32-a8b8-bed937562e92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7da3cf6f-ad4c-4ed0-ae04-3ae112d54a34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>527317be-bba2-4a19-8fad-23def5621b1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e678c7ef-b070-4761-8039-10f2fe3b8601</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8cd4649-1545-40da-b4fd-601c7330ed27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c68b907-0fa8-494a-9bce-feb7788efcb7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0e96ed4-9f82-4d03-aed6-3ce75a564a55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SD FLOW/SD FLOW_Meeting</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4029f530-1bf5-4ff2-9c17-65642cccb760</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d4875971-fb74-45cb-b32b-2f39556a0450</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SD FLOW/SD FLOW_Offer</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f61c318a-4494-4bff-a0f2-57fbd48e9a0b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SD FLOW/SD FLOW_Offer_Confirmations</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4057ad21-c7c0-4f35-aee8-146c9aabafee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SD FLOW/SD FLOW_Offer_Archive</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d9c7b634-f8db-4367-ba13-032f1ccd28df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SD FLOW/SD FLOW_Contract_Skip</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2c5be9ef-16f8-4f12-aae2-7db989e848ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SD FLOW/SD FLOW_BR_Advance_and_BI</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1bfaf9c0-667f-4383-b21c-e882001948f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SD FLOW/SD FLOW_RE</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3cde458b-e89c-4b95-8547-537c58b9b411</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SD FLOW/SD FLOW SaleOrder_from_Vendor</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>acfe2e88-3e8b-4645-86a4-cdc2c30a3000</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SD FLOW/SD FLOW Purchase_req</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
