<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SerialNBhandover</name>
   <tag></tag>
   <elementGuidId>a4b2048c-3861-4df2-b9e5-49443184ba62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[7]/div[1]/div/div/form/div/div[4]/div/div[1]/div[2]/table/tbody/tr[4]/td[2]/input[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
